### ISSUE TITLE
Styling errors in styleguide itself

### ISSUE THREAD

**Issue by samcarlinone** [livingstyleguide/livingstyleguide#201] opened 2016-07-08 20:06 UTC
I am using the integrated rails with version 2.0.0.pre.4, and the relevant parts of my project structure look like this

/app/assets/stylesheets/styleguide.html.lsg
/angular/css/**/*.scss

It works and I can create sections with .lsg files, however the page itself doesn't allow scrolling and the colors filter produces faulty output

Any ideas?

![image](https://cloud.githubusercontent.com/assets/18744198/16700022/aaa93c7c-4525-11e6-8758-ee6fc2163541.png)

![image](https://cloud.githubusercontent.com/assets/18744198/16700061/e396b01e-4525-11e6-9b22-f624ceeca426.png)

Color page too
![image](https://cloud.githubusercontent.com/assets/18744198/16700111/370a3cb6-4526-11e6-94f7-7f40b1fe67d4.png)

![image](https://cloud.githubusercontent.com/assets/18744198/16700121/3e849d2e-4526-11e6-996a-59e602c4ef6b.png)

**Comment by hagenburger** [comment] 2016-07-08 20:10
Could you maybe upload the HTML file somewhere so I can test the scrolling? What’s the issue with the color filter?

**Comment by samcarlinone** [comment] 2016-07-08 20:18
Here it is, the color filter output doesn't align with the table and colors like green aren't visible unless hovered
[GSS Style Guide.zip](https://github.com/livingstyleguide/livingstyleguide/files/355047/GSS.Style.Guide.zip)

**Comment by hagenburger** [comment] 2016-07-08 20:45
For the scrolling, I think this is caused by /home/sam/global-specimen-solutions/angular/css/shared/_globals.scss. You could override it:

``` lsg
@scss !global {
  .lsg,
  html {
    height: auto;
    overflow-x: auto;
    overflow-y: auto;
  }
}
```

----

The colors seem to be a background and z-index issue. A quick fix could be:

``` lsg
@scss !global {
  .lsg-color-swatch-value {
    z-index: 1;
    position: relative;
  }
  .lsg-color-swatch::before {
    z-index: 0;
  }
}
```

I’m going to check if this could be a bug in the Gem or it’s limited to your project.

**Comment by samcarlinone** [comment] 2016-07-08 20:54
Thanks for replying so quickly, this is a pretty awsome project :+1: 

I wonder, could you use something like shadow dom to isolate the styleguide from the project?

**Comment by samcarlinone** [comment] 2016-07-11 12:40
Or what about scoped CSS? https://css-tricks.com/saving-the-day-with-scoped-css/

**Comment by hagenburger** [comment] 2016-07-11 20:26
Shadow DOM sounds interesting, but one of the goals of a style guide is testing: You can open the style guide in every browser and easily test all components in one/few HTML pages without having the trouble of slow applications, logins, …

Can I use looks quite bad for Shadow DOM at the moment :(
http://caniuse.com/#search=shadow%20dom

But I’m planning some good old Iframe support.

I’m closing this as the original issue is fixed from my perspective. I’m happy to further discuss other topics :)

**Closed by hagenburger** 2016-07-11 20:26 UTC

**Comment by samcarlinone** [comment] 2016-07-11 20:51
OK, thanks for the help. When you say planning iframe support I assume you mean at some point in the future?

**Comment by hagenburger** [comment] 2016-07-11 20:53
Yes. I’ll need to do some planning now that 2.0.0 is released. Blog posts have some higher priority right now.

**Comment by alexlawrence** [comment] 2016-08-31 19:45
Sorry to comment on a closed issue but I´m getting the same z-index issue with the color swatches. Is this an issue/bug of livingstyleguide or is this caused by custom styles?

**Comment by hagenburger** [comment] 2016-08-31 20:30
In the case mentioned above the the problems have been caused by global CSS of the project. In your case I would need more information or the code.
