### ISSUE TITLE
Windows 10: installing livingstyleguide -> 'redcarpet' native gem requires installed build tools

### ISSUE THREAD

**Issue by HansS** [livingstyleguide/livingstyleguide#193] opened 2016-05-16 16:15 UTC
Hans@HP-HANS C:\Users\Hans                                            Hans@HP-HANS C:\Users\Hans                                            
> gem install livingstyleguide                                        
Fetching: tilt-2.0.4.gem (100%)                                       
Successfully installed tilt-2.0.4                                     
Fetching: thor-0.19.1.gem (100%)                                      
Successfully installed thor-0.19.1                                    
Fetching: sass-3.4.22.gem (100%)                                      
Successfully installed sass-3.4.22                                    
Fetching: redcarpet-3.3.4.gem (100%)                                  
ERROR:  Error installing livingstyleguide:                            
        The 'redcarpet' native gem requires installed build tools.    
                                                                      
Please update your PATH to include build tools or download the DevKit 
from 'http://rubyinstaller.org/downloads' and follow the instructions 
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'    
> gem install livingstyleguide                                        
Fetching: tilt-2.0.4.gem (100%)                                       
Successfully installed tilt-2.0.4                                     
Fetching: thor-0.19.1.gem (100%)                                      
Successfully installed thor-0.19.1                                    
Fetching: sass-3.4.22.gem (100%)                                      
Successfully installed sass-3.4.22                                    
Fetching: redcarpet-3.3.4.gem (100%)                                  
ERROR:  Error installing livingstyleguide:                            
        The 'redcarpet' native gem requires installed build tools.    
                                                                      
Please update your PATH to include build tools or download the DevKit 
from 'http://rubyinstaller.org/downloads' and follow the instructions 
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'

**Comment by hagenburger** [comment] 2016-05-16 19:09
Duplicate of #194. Closing this one.

**Closed by hagenburger** 2016-05-16 19:09 UTC
